//tinfo200:[2021-03-13-<rfj4>-dykstra1] Added this code directly from the tutorial. The Enrollment property again serves as a navigation property in correspondence to any number of Enrollment entities.
// There is a DatabaseGenerated attribute here that allows the primary key to be entered rather than generated by the database.


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public class Course
    {
        [DatabaseGenerated (DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}
